# Generated by Django 5.1.3 on 2025-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
            },
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
