# Generated by Django 5.1.3 on 2025-08-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_messages_delete_userdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="is_register",
            field=models.BooleanField(default=False, verbose_name="is register"),
        ),
        migrations.AddField(
            model_name="messages",
            name="value_en",
            field=models.TextField(null=True, verbose_name="value"),
        ),
        migrations.AddField(
            model_name="messages",
            name="value_ru",
            field=models.TextField(null=True, verbose_name="value"),
        ),
        migrations.AddField(
            model_name="messages",
            name="value_uz",
            field=models.TextField(null=True, verbose_name="value"),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="chat_id",
            field=models.CharField(max_length=255, unique=True, verbose_name="chat id"),
        ),
    ]
