# Generated by Django 5.1.3 on 2025-08-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botuser_is_register_messages_value_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='lang',
            field=models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=255, verbose_name='lang'),
        ),
    ]
