# Generated by Django 5.1.3 on 2025-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_botuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone'),
        ),
    ]
