# Generated by Django 5.1.3 on 2025-08-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_botuser_full_name_botuser_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("name_uz", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="name")),
                (
                    "service",
                    models.CharField(
                        choices=[("hotel", "hotel"), ("transfer", "transfer"), ("mini_tour", "mini_tour")],
                        default="hotel",
                        max_length=255,
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Address",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("name_uz", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="name")),
                (
                    "service",
                    models.CharField(
                        choices=[("hotel", "hotel"), ("transfer", "transfer"), ("mini_tour", "mini_tour")],
                        default="hotel",
                        max_length=255,
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="HotelModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("name_uz", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_ru", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("name_en", models.CharField(max_length=255, null=True, verbose_name="name")),
                ("desc", models.TextField(verbose_name="desc")),
                ("desc_uz", models.TextField(null=True, verbose_name="desc")),
                ("desc_ru", models.TextField(null=True, verbose_name="desc")),
                ("desc_en", models.TextField(null=True, verbose_name="desc")),
                ("category", models.ManyToManyField(to="bot.categorymodel")),
                ("location", models.ManyToManyField(to="bot.addressmodel")),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hotel",
                "db_table": "hotels",
            },
        ),
    ]
