# Generated by Django 5.1.3 on 2025-08-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_addressmodel_categorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='desc_ru',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='desc_uz',
            field=models.TextField(blank=True, null=True, verbose_name='desc'),
        ),
    ]
