# Generated by Django 5.1.3 on 2025-08-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_categorymodel_desc_categorymodel_desc_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full_name')),
                ('passport', models.FileField(upload_to='passports/', verbose_name='passport')),
                ('passport_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='passport_file_id')),
                ('date', models.CharField(max_length=255, verbose_name='date')),
                ('notionality', models.CharField(max_length=255, verbose_name='notionality')),
                ('birth_date', models.CharField(max_length=255, verbose_name='birth date')),
                ('service', models.CharField(max_length=255, verbose_name='service')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=255, verbose_name='status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
