# Generated by Django 5.1.3 on 2025-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_visaorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaorder',
            name='notionality',
        ),
        migrations.AddField(
            model_name='visaorder',
            name='nationality',
            field=models.CharField(max_length=255, null=True, verbose_name='nationality'),
        ),
    ]
