# Generated by Django 5.1.3 on 2025-08-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_remove_visaorder_notionality_visaorder_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaorder',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='visaorder',
            name='passport_file_id',
        ),
        migrations.AddField(
            model_name='visaorder',
            name='passport_back',
            field=models.FileField(null=True, upload_to='passports/', verbose_name='passport back'),
        ),
        migrations.AddField(
            model_name='visaorder',
            name='passport_back_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='passport_back_file_id'),
        ),
        migrations.AddField(
            model_name='visaorder',
            name='passport_front',
            field=models.FileField(null=True, upload_to='passports/', verbose_name='passport front'),
        ),
        migrations.AddField(
            model_name='visaorder',
            name='passport_front_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='passport_front_file_id'),
        ),
    ]
