# Generated by Django 5.1.3 on 2025-08-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_visaorder_passport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(max_length=255, verbose_name='serrvice type')),
                ('date', models.CharField(max_length=255, verbose_name='date')),
                ('passanger_count', models.CharField(max_length=255, verbose_name='passanger_count')),
                ('goods', models.CharField(max_length=255, verbose_name='goods')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.categorymodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.botuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
