# Generated by Django 5.1.3 on 2025-08-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_transferorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=255, verbose_name='status'),
        ),
    ]
