# Generated by Django 5.1.3 on 2025-08-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_hotelorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='hotel/', verbose_name='file')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.hotelmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
