# Generated by Django 5.1.3 on 2025-08-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='video', max_length=255, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bot.hotelmodel'),
        ),
    ]
