# Generated by Django 5.1.3 on 2025-08-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_file_file_type_alter_file_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='file id'),
        ),
    ]
