# Generated by Django 5.1.3 on 2025-08-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_file_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelorder',
            name='power_type',
            field=models.CharField(default='RO', max_length=255, verbose_name='power type'),
        ),
        migrations.AddField(
            model_name='hotelorder',
            name='transfer',
            field=models.BooleanField(default=False, verbose_name='transfer'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='hotel/', verbose_name='file'),
        ),
    ]
