# Generated by Django 5.1.3 on 2025-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_packagemodel_minitourorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='desc',
            field=models.TextField(null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='desc'),
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='desc_uz',
            field=models.TextField(null=True, verbose_name='desc'),
        ),
    ]
